### ISSUE TITLE
Unhandled exception with AllowUnApproved

### ISSUE THREAD

**Issue by Mace404** [CodeStix/Beat-Modder#8]
Nice update!

Getting an error on startup though when AllowUnApproved is set to True in the BeatModder.exe.config file and the checkbox is set in the app:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Stx.BeatModder.FormMain.<checkBoxAllowNonApproved_CheckedChanged>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by CodeStix** [comment]
Woah, thanks for testing, much appreciated!
I will try reproduce the problem rignt now.

**Comment by Mace404** [comment]
Did you find the problem?

**Comment by CodeStix** [comment]
Yes I fixed it, and I added complete unapproved mod support (it is displayed in a different color). Expect an update rolling out in a few days. It would probably release with 'offline' mod installs too.

**Comment by Mace404** [comment]
Awesome, awaiting the release.
